/// One upstream licence or notice file, reproduced verbatim.
class NoticeSection {
  /// The file's path inside the upstream tree, e.g. `LICENSE`.
  final String upstreamPath;

  /// A short human title for the section heading.
  final String title;

  /// The file's exact text. Never summarised, reflowed, or truncated: this is
  /// a licence obligation, not prose.
  final String text;

  NoticeSection({
    required this.upstreamPath,
    required this.title,
    required this.text,
  });
}

/// The upstream licence and notice files copied into `THIRD_PARTY_NOTICES.md`.
///
/// Order is fixed so the rendered file is a pure function of the pinned tree.
const upstreamNoticeFiles = <String, String>{
  'LICENSE': 'Apache License 2.0',
  'LICENSE-3RD-PARTY.txt': 'third-party license inventory',
};

/// Renders the whole of `THIRD_PARTY_NOTICES.md`.
///
/// The file is generated end to end rather than patched in place, so a second
/// fetch at the same pin reproduces it byte for byte. The preamble keeps the
/// PRD §17 disclaimer and trademark notice; the sections below it are upstream
/// text, unmodified.
String renderThirdPartyNotices({
  required String repo,
  required String tag,
  required String commit,
  required List<NoticeSection> sections,
}) {
  final buffer = StringBuffer()
    ..writeln('# Third-party notices')
    ..writeln()
    ..writeln(
      'Unofficial Dart/Flutter SDK for the open-source Trust Wallet Core '
      'library. Not affiliated with or endorsed by Trust Wallet.',
    )
    ..writeln()
    ..writeln(
      'The Dart and Flutter code in this repository is MIT licensed; see '
      '[LICENSE](LICENSE).',
    )
    ..writeln()
    ..writeln(
      'The native artifacts distributed with `wallet_core_flutter_native` are '
      'builds of Trust Wallet Core (<https://github.com/$repo>), which is '
      'licensed under the Apache License, Version 2.0. The licence and notice '
      'text below is reproduced verbatim from the upstream tree at the commit '
      'pinned in `compat_manifest.json`.',
    )
    ..writeln()
    ..writeln(
      '"Trust Wallet" is a third-party trademark. No Trust Wallet logos or '
      'brand assets are used here.',
    )
    ..writeln()
    ..writeln('| Field | Value |')
    ..writeln('|---|---|')
    ..writeln('| Upstream repository | `$repo` |')
    ..writeln('| Pinned tag | `$tag` |')
    ..writeln('| Pinned commit | `$commit` |')
    ..writeln()
    ..writeln(
      'This file is generated by `melos run upstream:fetch` '
      '(`tools/upstream`). Do not hand-edit the sections below; they are '
      'copies of upstream files.',
    );

  for (final section in sections) {
    final fence = '`' * fenceLengthFor(section.text);
    buffer
      ..writeln()
      ..writeln(
        '## `${section.upstreamPath}` — $repo @ $tag ($commit) — '
        '${section.title}',
      )
      ..writeln()
      ..writeln('${fence}text');
    // Verbatim upstream text. Trailing whitespace and blank lines are part of
    // the file, so it is emitted unchanged inside a fenced block.
    buffer.write(section.text);
    if (!section.text.endsWith('\n')) buffer.write('\n');
    buffer.writeln(fence);
  }

  return buffer.toString();
}

/// The number of backticks needed to fence [text] without the text closing the
/// fence itself: one more than the longest backtick run inside it, and never
/// fewer than three.
int fenceLengthFor(String text) {
  var longest = 0;
  var run = 0;
  for (final unit in text.codeUnits) {
    if (unit == 0x60) {
      run++;
      if (run > longest) longest = run;
    } else {
      run = 0;
    }
  }
  return longest + 1 < 3 ? 3 : longest + 1;
}
