import 'dart:convert';
import 'dart:io';

import 'package:test/test.dart';
import 'package:wcf_tool_inventory/symbol_names.dart';
import 'package:wcf_tool_upstream/dist.dart';

/// `bin/symbols.dart`'s two outputs, relative to this package.
const _generatedNames =
    '../../packages/wallet_core_flutter_bindings/lib/src/generated/ffi/'
    'symbol_names.dart';
const _inventoryJson =
    '../../packages/wallet_core_flutter_bindings/lib/src/generated/'
    'inventory.json';

/// The ffigen output and the release-asset headers, relative to this package.
const _generatedBindings =
    '../../packages/wallet_core_flutter_bindings/lib/src/generated/ffi/'
    'wallet_core_bindings.dart';
const _distRoot = '../../$defaultDistDestination';

/// The entries of one `const List<String> <name> = <String>[…]` declaration.
List<String> _entries(String source, String name) {
  final start = source.indexOf('const List<String> $name = <String>[');
  if (start < 0) fail('no declaration of $name');
  final end = source.indexOf('];', start);
  if (end < 0) fail('unterminated declaration of $name');
  return RegExp(
    "'([A-Za-z0-9_]+)'",
  ).allMatches(source.substring(start, end)).map((m) => m[1]!).toList();
}

void main() {
  group('renderSymbolNames', () {
    test('sorts the names and does not care what order they arrived in', () {
      const scrambled = ['TWB', 'stringForHRP', 'TWA', 'hrpForString'];
      final source = renderSymbolNames(scrambled);

      expect(_entries(source, 'boundFunctionNames'), [
        'TWA',
        'TWB',
        'hrpForString',
        'stringForHRP',
      ]);
      expect(
        renderSymbolNames(scrambled.reversed),
        equals(source),
        reason: 'the output is a function of the set, not of its order',
      );
    });

    test('is deterministic and ends with a newline', () {
      const names = ['TWA', 'TWB', 'stringForHRP'];
      final source = renderSymbolNames(names);
      expect(renderSymbolNames(names), equals(source));
      expect(source, endsWith(';\n'));
      expect(source, isNot(contains('\n\n\n')));
    });

    test('deduplicates', () {
      expect(
        _entries(
          renderSymbolNames(['TWA', 'TWA', 'TWB']),
          'boundFunctionNames',
        ),
        ['TWA', 'TWB'],
      );
    });

    test('splits out the TW-prefixed subset the export gate uses', () {
      final source = renderSymbolNames([
        'TWA',
        'TWB',
        'stringForHRP',
        'hrpForString',
      ]);
      expect(_entries(source, 'exportedTwFunctionNames'), ['TWA', 'TWB']);
      expect(source, contains('Sorted, 4 names'));
      expect(source, contains('Sorted, 2 names'));
    });

    test('carries the generated-file header: regenerate command, rule 1, and '
        'the disclaimer', () {
      final source = renderSymbolNames(const ['TWA']);
      expect(source, startsWith('// GENERATED FILE — DO NOT EDIT.'));
      expect(source, contains('melos run gen:ffi'));
      expect(source, contains('AGENTS.md rule 1'));
      expect(
        source,
        contains('Not affiliated with or endorsed by Trust Wallet.'),
      );
    });
  });

  group('the committed symbol_names.dart', () {
    // Present in every checkout; regenerated by `melos run gen:ffi`.
    final file = File(_generatedNames);
    final inventory = File(_inventoryJson);

    test(
      'holds the 466 bound functions and the 464 TW* ones, and agrees with '
      'inventory.json name for name',
      () {
        final source = file.readAsStringSync();
        final bound = _entries(source, 'boundFunctionNames');
        final exported = _entries(source, 'exportedTwFunctionNames');

        expect(bound, hasLength(466));
        expect(exported, hasLength(464));
        expect(exported, equals(bound.where((n) => n.startsWith('TW'))));
        expect(
          bound.toSet().difference(exported.toSet()),
          equals({'hrpForString', 'stringForHRP'}),
        );

        final symbols =
            (jsonDecode(inventory.readAsStringSync())
                    as Map<String, Object?>)['symbols']!
                as Map<String, Object?>;
        final fromInventory =
            symbols.entries
                .where((e) {
                  final row = e.value! as Map<String, Object?>;
                  return row['kind'] == 'function' &&
                      row['in_generated'] == true;
                })
                .map((e) => e.key)
                .toList()
              ..sort();

        expect(
          bound,
          equals(fromInventory),
          reason: 'both files come from one scan of the generated bindings',
        );
      },
      skip: file.existsSync() && inventory.existsSync()
          ? false
          : 'needs `melos run gen:ffi`',
    );

    test('is exactly what renderSymbolNames would write for those names', () {
      final source = file.readAsStringSync();
      expect(
        renderSymbolNames(_entries(source, 'boundFunctionNames')),
        equals(source),
        reason: 'a hand edit, or a stale file, fails here and in --check',
      );
    }, skip: file.existsSync() ? false : 'needs `melos run gen:ffi`');
  });

  group('bin/symbols.dart --check', () {
    // The real inputs: the tool reads the pinned headers and the committed
    // bindings, so this exercises the gate `melos run inventory:check` runs and
    // not a stand-in for it.
    final ready =
        Directory(_distRoot).existsSync() &&
        File(_generatedBindings).existsSync() &&
        File(_generatedNames).existsSync();

    // From the repository root and with the tool's own defaults, which is how
    // `melos run inventory:check` invokes it: the paths it writes into
    // inventory.json are root-relative and would differ otherwise.
    ProcessResult run(List<String> extra) => Process.runSync(
      Platform.resolvedExecutable,
      <String>['run', 'tools/inventory/bin/symbols.dart', '--check', ...extra],
      workingDirectory: '../..',
    );

    test('passes on the committed generated files', () {
      final result = run(const <String>[]);
      expect(
        result.exitCode,
        0,
        reason: 'stdout: ${result.stdout}\nstderr: ${result.stderr}',
      );
      expect(result.stdout, contains('symbol_names.dart: up to date'));
    }, skip: ready ? false : 'needs `melos run upstream:fetch` and `gen:ffi`');

    test('fails when symbol_names.dart is stale, the way it does for '
        'inventory.json', () {
      final directory = Directory.systemTemp.createTempSync('wcf-names-');
      addTearDown(() => directory.deleteSync(recursive: true));
      // One name dropped from the bound list: the smallest edit a hand
      // change or a pin bump could leave behind.
      final staleContents = File(
        _generatedNames,
      ).readAsStringSync().replaceFirst("  'TWAESDecryptCBC',\n", '');
      final stale = File('${directory.path}/symbol_names.dart')
        ..writeAsStringSync(staleContents);

      final result = run(<String>['--names-out', stale.absolute.path]);
      expect(result.exitCode, 1);
      expect(result.stderr, contains('is stale'));
      expect(result.stderr, contains('melos run gen:ffi'));
      expect(
        stale.readAsStringSync(),
        equals(staleContents),
        reason: '--check never writes',
      );
    }, skip: ready ? false : 'needs `melos run upstream:fetch` and `gen:ffi`');
  });
}
